name: "App Insights for GitHub Actions"
author: "LobsterInk"
description: "Send custom event to Azure Application Insights."
branding:
  icon: "monitor"
  color: "blue"
inputs:
  instrumentation-key:
    description: "Azure Application Insights Instrumentation Key"
    required: true
    default: "no_instrumentation_key"
  event-name:
    description: "Name of the custom event"
    required: true
  event-data:
    description: "JSON metadata for the custom event"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl https://dc.services.visualstudio.com/v2/track -d @- <<BODY
        {
          "name": "EventData",
          "time": "$(date --utc +%FT%T.%3NZ)",
          "iKey": "${{ inputs.instrumentation-key }}",
          "data": {
            "baseType": "EventData",
            "baseData": {
              "name": "${{ inputs.event-name }}",
              "properties": {
                "workflow": "${{ github.workflow }}",
                "run_number": "${{ github.run_number }}",
                "actor": "${{ github.actor }}",
                "repository": "${{ github.repository }}",
                "event_name": "${{ github.event_name }}",
                "data": ${{ github.event_data}}
              }
            }
          }
        }
        BODY
      shell: bash